<?php

/**
 * @file
 * Contains table_select.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function table_select_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the table_select module.
    case 'help.page.table_select':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}
